### ISSUE TITLE
Document and clarify advantages of using this vs express-jwt and jwks-rsa

### ISSUE THREAD

**Issue by danmana** [auth0/node-oauth2-jwt-bearer#48]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Currently, there is an inconsistency in the documentation regarding Node.js quickstarts.

* https://auth0.com/docs/quickstart/backend/nodejs recommends using `express-oauth2-jwt-bearer`
* https://github.com/auth0-samples/auth0-express-api-samples/tree/master/01-Authorization-RS256 uses `express-oauth2-jwt-bearer`
* the Node.js Quickstart tab when creating an API from Auth0 ui recommends `express-jwt`, `jwks-rsa`
* https://github.com/auth0-blog/auth0-express-js-sample also uses `express-jwt`, `jwks-rsa`

Is there some documentation about which libraries are recommended and why?
What was the rationale behind creating this new library `express-oauth2-jwt-bearer`? 
To me, it looks like it contains both features of `express-jwt` and `express-jwt-permissions` all in one, which is nice. Is that the main advantage?

### Describe the ideal solution

1. Align Quickstart documentation.
2. Document what the advantages of this lib are over `express-jwt`
3. (optional) Migration guide `express-jwt` to `express-oauth2-jwt-bearer`

## Alternatives and current work-arounds

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by adamjmcgrath** [comment]
Hi @danmana - thanks for raising this

> Align Quickstart documentation.

I see that the Quick Start tab in the API Details page of the manage dashboard is using `express-jwt` - will raise some work to fix that, thanks for the heads up

> Document what the advantages of this lib are over express-jwt

We have a new blog post coming out soon(ish) - I'll bug the team that schedules these. There's not a lot I can do about the old blog posts, but I'll check

> (optional) Migration guide express-jwt to express-oauth2-jwt-bearer

Thanks for the suggestion, since the API is fairly simple, I think I'll just leave the docs to speak for themselves. But I'll monitor feedback to see if there's more demand for this.

Also - I have [a PR](https://github.com/auth0/express-jwt/pull/268) to add a maintenance notice to `express-jwt` - I'll bug the maintainer to merge it.

Closing this as there's no changes required in this project
