### ISSUE TITLE
Unble to add the express package on node 17

### ISSUE THREAD

**Issue by evographics** [auth0/node-oauth2-jwt-bearer#51]
Hello,

I tried to install the package with the command `yarn add express-oauth2-jwt-bearer`

but I got this error 

`The engine "node" is incompatible with this module. Expected version "12.19.0 || ^14.15.0 || ^16.13.0". Got "17.4.0"`

I know it's related to my node js version, but I need node 17 for other packages. Instead of checking a specific version, could the package be installed on a version greater than node 12?

Node js is updated very often and I will keep it up to date, so this is a problem.

Thank you.

**Comment by adamjmcgrath** [comment]
Hi @evographics - thanks for raising this

This SDK uses `jose` for cryptographically verifying JWTs, which in turn uses low level Node `crypto` APIs. For that reason we can only guarantee that this will work in the same versions of Node that `jose` supports. `jose` only supports Node LTS versions (see https://github.com/panva/jose/issues/262). Since 17 is not LTS, we can't guarantee support for it. 

> Node js is updated very often and I will keep it up to date, so this is a problem.

The next Node LTS starts [2022-10-25](https://nodejs.org/en/about/releases/) - so we'll make sure to update the `engines` requirement around that time.

You can ignore this requirement (at your own risk) by adding the `--ignore-engines` argument to your `yarn` command.

Closing this, feel free to ping me if you want to continue the conversation
