### ISSUE TITLE
Allow for JWT to be in headers other than Authorization

### ISSUE THREAD

**Issue by purejgleason** [auth0/node-oauth2-jwt-bearer#61]
### Describe the problem you'd like to have solved

The Google API Gateway docs suggest that the Authorization header is forwarded to another header. This header is then base64 encoded. I would like a configuration to be able to use a header name other than authorization. It looks like the change would need to happen here...

https://github.com/auth0/node-oauth2-jwt-bearer/blob/47a64302bd077601701dfcbe34cbdf058431de88/packages/oauth2-bearer/src/get-token.ts

More information on the Google requirements...

https://cloud.google.com/endpoints/docs/openapi/authenticating-users-custom#receiving_authenticated_results_in_your_api

### Describe the ideal solution

I can pass a config to `bearer.auth` to tell it the header name I would like to use.

## Alternatives and current work-arounds

Google does still provide the Authorization header, however, they advise against using it.

**Comment by adamjmcgrath** [comment]
HI @purejgleason - thanks for raising this

From the [docs you've shared](https://cloud.google.com/endpoints/docs/openapi/authenticating-users-custom#receiving_authenticated_results_in_your_api) it looks like the ESP service performs JWT authentication for you then "ESP will send the authentication result in the X-Endpoint-API-UserInfo to the backend API". So it looks like you either want to use this SDK _or_ the ESP service to perform authentication.

This SDK expects a bearer JWT (not "a string that base64url encodes a JSON object" of the "authentication result") so even if it accepted the `X-Endpoint-API-UserInfo`, JWT validation would still fail, because it would be getting a JWT (and you wouldn't want to do this anyway, since the JWT should already have been validated by ESP)
